version: "3"
services:
  loginmicroservices:
    image: s3781403/loginmicroservice
    tty: true
    build:
      context: BackEnd/loginmicroservices
      dockerfile: Dockerfile
    volumes:
      - /data/app-backend
    ports:
      - "3000:3000"

  booksmicroservices:
    image: s3781403/booksmicroservice
    tty: true
    build:
      context: BackEnd/booksmicroservices
      dockerfile: Dockerfile
    volumes:
      - /data/app-backend
    ports:
      - "8081:8081"