version: "3"
services:
  loginmicroservices:
    image: s3781403/loginmicroservice
    build:
      context: ./loginmicroservices
      dockerfile: Dockerfile
    volumes:
      - /data/app-backend
    ports:
      - "3000:3000"

  booksmicroservices:
    image: s3781403/booksmicroservice
    build:
      context: ./booksmicroservices
      dockerfile: Dockerfile
    volumes:
      - /data/app-backend
    ports:
      - "8081:8081"