version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-ecs: circleci/aws-ecs@1.2.0
jobs:
  test:
    working_directory: /dockerapp1
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Run test build
          command: |
            docker-compose up -d
workflows:
  test-build-deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          setup-remote-docker: true 
          repo: bookeroo-server
          tag: ${CIRCLE_BRANCH}_${CIRCLE_SHA1},${CIRCLE_BRANCH}_latest
          filters:
            branches:
              only:
                - master
                - development

      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          cluster-name: bookeroo-server-development 
          family: runDockerContainers-development 
          service-name: bookeroo-server 
          docker-image-for-job: docker:17.05.0-ce-git 
          filters:
            branches:
              only:
                - development

      - approve-deploy:
          type: approval
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only:
                - master

      - aws-ecs/deploy-service-update:
            requires:
              - approve-deploy
            cluster-name: BookerooServer-production 
            family: runDockerContainers 
            service-name: bookeroo-server 
            docker-image-for-job: docker:17.05.0-ce-git 
            filters:
              branches:
                only:
                  - master



