version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-ecs: circleci/aws-ecs@2.2.1
jobs:
  test:
    working_directory: /dockerapp1
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Run test build
          command: |
            docker-compose up -d
  createImage:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: "bookeroo-server"
          tag: "${CIRCLE_BRANCH}_${CIRCLE_SHA1},${CIRCLE_BRANCH}_latest"
          filters:
            branches:
              only:
                - master
                - development
  deployDevelopmentBuild:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - aws-ecs/deploy-service-update:
          name: deploy-development
          aws-region: AWS_DEFAULT_REGION
          requires:
            - createImage
          family: "runDockerContainers-development"
          cluster-name: "bookeroo-server-development"
          service-name: "bookeroo-server"
          container-image-name-updates: "container=bookeroo_server_development,tag=${CIRCLE_BRANCH}_${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - development
  deployProductionBuild:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - aws-ecs/deploy-service-update:
          name: deploy-production
          aws-region: AWS_DEFAULT_REGION
          requires:
            - createImage
          family: "runDockerContainers"
          cluster-name: "BookerooServer-production"
          service-name: "bookeroo-server"
          container-image-name-updates: "container=bookeroo_server_production,tag=${CIRCLE_BRANCH}_${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - master




workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - createImage
      - deployDevelopmentBuild
      - deployProductionBuild



